import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { lstat, mkdir, mkdtemp, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const legacyPath = "/Website";
const marker = ".legacy-paths.json";
const generator = "scripts/legacy-paths.mjs";
const digest = (bytes) => createHash("sha256").update(bytes).digest("hex");
const escapeHtml = (value) => value.replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");

export function redirectHtml(route, siteOrigin) {
  assert.ok(route.startsWith("/") && !route.startsWith("//") && !/[?#\\]/.test(route), "Expected an absolute local route");
  const target = escapeHtml(route);
  const canonical = escapeHtml(new URL(route, siteOrigin).href);
  // Serialising the route independently prevents a URL or filename from becoming script content.
  const scriptRoute = JSON.stringify(route).replaceAll("<", "\\u003c");
  return `<!doctype html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Page moved · Jacob Edenhofer</title>
<link rel="canonical" href="${canonical}">
<script>
const destination = new URL(${scriptRoute}, window.location.origin);
destination.search = window.location.search;
destination.hash = window.location.hash;
window.location.replace(destination.href);
</script>
<noscript><meta http-equiv="refresh" content="0; url=${target}"></noscript>
</head>
<body><main id="main-content"><h1>This page has moved</h1><p><a href="${target}">Continue to Jacob Edenhofer’s website</a>.</p></main></body>
</html>
`;
}

async function filesIn(directory, { ignore = () => false } = {}) {
  const files = [];
  async function visit(relative = "") {
    const entries = await readdir(path.join(directory, relative), { withFileTypes: true });
    for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name, "en"))) {
      const filename = path.posix.join(relative, entry.name);
      if (ignore(filename, entry)) continue;
      assert.ok(!entry.isSymbolicLink(), `Refusing symbolic link: ${filename}`);
      if (entry.isDirectory()) await visit(filename);
      else {
        assert.ok(entry.isFile(), `Expected a regular file: ${filename}`);
        files.push(filename);
      }
    }
  }
  await visit();
  return files;
}

async function checkExistingDestination(destination) {
  try { await lstat(destination); } catch (error) { if (error.code === "ENOENT") return; throw error; }
  const info = await lstat(destination);
  assert.ok(info.isDirectory() && !info.isSymbolicLink(), `${legacyPath} collides with an existing file or symbolic link`);
  let manifest;
  try { manifest = JSON.parse(await readFile(path.join(destination, marker), "utf8")); }
  catch { throw new Error(`${legacyPath} already exists and was not generated by ${generator}`); }
  assert.equal(manifest.generator, generator, `Unrecognised ${legacyPath} ownership marker`);
  assert.equal(manifest.version, 1, `Unsupported ${legacyPath} ownership marker`);
  const existing = await filesIn(destination);
  assert.deepEqual(existing.filter((name) => name !== marker).sort(), Object.keys(manifest.files).sort(), `${legacyPath} contains unexpected files`);
  for (const [filename, expected] of Object.entries(manifest.files)) {
    assert.equal(digest(await readFile(path.join(destination, filename))), expected, `Generated legacy file was modified: ${filename}`);
  }
}

export async function buildLegacyPaths({ outputDir = path.resolve("out"), publicDir = path.resolve("public"), basePath, siteOrigin }) {
  assert.equal(basePath, "", "Legacy redirects require a root deployment with an empty basePath");
  const origin = new URL(siteOrigin);
  assert.ok(/^https?:$/.test(origin.protocol) && origin.href === `${origin.origin}/`, "siteOrigin must be an HTTP(S) origin without a path");
  outputDir = path.resolve(outputDir);
  publicDir = path.resolve(publicDir);
  for (const relative of [path.relative(outputDir, publicDir), path.relative(publicDir, outputDir)]) {
    assert.ok(relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative), "Public assets and build output must be separate directories");
  }
  const rootHtml = await readFile(path.join(outputDir, "index.html"), "utf8");
  assert.ok(!rootHtml.includes(`${legacyPath}/_next/`), "Build still contains the old basePath; rebuild for the root address first");
  const destination = path.join(outputDir, legacyPath);
  await checkExistingDestination(destination);

  const exportedFiles = await filesIn(outputDir, {
    ignore: (filename) => filename.split("/").some((part) => part.startsWith(".") || part.startsWith("_") || part === "Website" || part === "404"),
  });
  const routes = exportedFiles.filter((filename) => path.posix.basename(filename) === "index.html").map((filename) => {
    const directory = path.posix.dirname(filename);
    return directory === "." ? "/" : `/${directory.split("/").map(encodeURIComponent).join("/")}/`;
  });
  assert.ok(routes.includes("/"), "The export has no home page");

  // Only files intentionally placed in public/ are compatibility assets; never copy source or _next.
  const assets = await filesIn(publicDir);
  const entries = new Map(routes.map((route) => [`${decodeURIComponent(route).slice(1)}index.html`, Buffer.from(redirectHtml(route, origin.origin))]));
  for (const filename of assets) {
    assert.ok(!filename.split("/").some((part) => part.startsWith(".") || part === "Website" || part === "_next"), `Unexpected public asset: ${filename}`);
    assert.ok(!entries.has(filename), `Public asset collides with a legacy page: ${filename}`);
    const bytes = await readFile(path.join(publicDir, filename));
    assert.deepEqual(await readFile(path.join(outputDir, filename)), bytes, `Exported asset differs from public source: ${filename}`);
    entries.set(filename, bytes);
  }

  const staging = await mkdtemp(path.join(outputDir, ".legacy-stage-"));
  try {
    const hashes = {};
    for (const [filename, bytes] of [...entries].sort(([a], [b]) => a.localeCompare(b, "en"))) {
      const target = path.join(staging, filename);
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, bytes);
      hashes[filename] = digest(bytes);
    }
    await writeFile(path.join(staging, marker), `${JSON.stringify({ generator, version: 1, files: hashes }, null, 2)}\n`);
    await rm(destination, { recursive: true, force: true });
    await rename(staging, destination);
  } finally {
    await rm(staging, { recursive: true, force: true });
  }
  return { routes, assets };
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const { basePath, siteOrigin } = await import("../site.config.mjs");
  const result = await buildLegacyPaths({ basePath, siteOrigin });
  console.log(`Preserved ${result.routes.length} legacy page URLs and ${result.assets.length} public asset URLs under ${legacyPath}/.`);
}
